"""initial

Revision ID: 86b5b57a9a23
Revises: 
Create Date: 2025-03-14 13:41:01.581415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86b5b57a9a23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.TEXT(), nullable=False, comment='User id in Firebase.'),
    sa.Column('email', sa.TEXT(), nullable=False, comment='User email.'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique index of element (type UUID)'),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Date and time of create (type TIMESTAMP)'),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Date and time of last update (type TIMESTAMP)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('id', name=op.f('uq__users__id'))
    )
    op.create_index(op.f('ix__users__email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix__users__uid'), 'users', ['uid'], unique=True)
    op.create_table('games',
    sa.Column('title', sa.TEXT(), nullable=False, comment='Game title.'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='Game description.'),
    sa.Column('cover_image', sa.TEXT(), nullable=False, comment='Game cover image url.'),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='Author identifier.'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique index of element (type UUID)'),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Date and time of create (type TIMESTAMP)'),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Date and time of last update (type TIMESTAMP)'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk__games__author_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__games')),
    sa.UniqueConstraint('id', name=op.f('uq__games__id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_index(op.f('ix__users__uid'), table_name='users')
    op.drop_index(op.f('ix__users__email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
